version: '3'
services:
  app-mysql-server:
    image: mysql:5.7
    container_name: app-mysql-server
    environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=bchio
    - MYSQL_PASSWORD=root
    ports:
    - 3333:3306
    volumes:
    - /data/mysql
  bchio:
    image: bchio
    container_name: bchio
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
    - app-mysql-server
    ports:
    - 8086:8086
    volumes:
    - /data/bchio/